### ISSUE TITLE
Feature request: Search YouTube by location and subscriber count

### ISSUE THREAD

**Issue by makersmaze123** [mattwright324/youtube-geofind#23]
To be able to find youtubers that have clout within an area, we need to see their subscriber numbers and location at the same time. E.G UK - subs between 10k - 50k, 50k - 100k etc

**Comment by mattwright324** [comment]
Unfortunately, it isn't possible to search results sorted by channel subscriber count. However, the closest alternatives that are available would be viewCount and videoCount. 

![image](https://user-images.githubusercontent.com/7717432/121910889-3c932300-ccfd-11eb-8a73-bc8676bcac06.png)

Some more detail about these sorting options from the [API docs](https://developers.google.com/youtube/v3/docs/search/list#order).

![image](https://user-images.githubusercontent.com/7717432/121911144-7d8b3780-ccfd-11eb-856c-9490558911a2.png)

I would definitely add additional search options to the project if Google made it available. However, it would have to be a suggestion sent to [Google IssueTracker](https://issuetracker.google.com/issues?q=componentid:186600%20status:open) instead.
