### ISSUE TITLE
"Sort by" isn't working.

### ISSUE THREAD

**Issue by snifer1981** [mattwright324/youtube-geofind#3]
"Sort by" isn't working.

**Comment by mattwright324** [comment]
Sort by does indeed work, however, are you referring to the sort order of the video list at the bottom of the page? Currently, the list does not represent the order the results came back and this may be an issue I can look into. The results themselves have been returned correctly based on the sort value used in the YouTube API query.

**Comment by snifer1981** [comment]
Yes, I'm talking about video list at the bottom of the page. Thanks for looking at.

**Comment by mattwright324** [comment]
41e3178dc3173ee35c8e27f76075155f84edada5 the table at the bottom of the list now represents the order that the results came back
