### ISSUE TITLE
Date-related searching not working

### ISSUE THREAD

**Issue by mattwright324** [mattwright324/youtube-geofind#6]
Not an issue with this application but YouTube as of 3/16.

https://issuetracker.google.com/issues/128673552

The bug affects the YouTube API and the YouTube site when searching ordered by date, nothing to be done but wait until things are fixed.

**Comment by snifer1981** [comment]
Looks like timeframe is affected, also. Not sure if it's a different bug.

**Comment by mattwright324** [comment]
It's all the same bug. Anything related to date & time has been broken... intentionally and temporarily from the sound of it but no official word from YouTube on why.

**Comment by mattwright324** [comment]
I guess here is actual 'official' word [from a Google employee](https://support.google.com/youtube/thread/2494861?msgid=2520468). Looks to be a measure to remove graphic content from recent terror attacks and they will update when they put things back to normal.

**Comment by mattwright324** [comment]
Google has re-enabled the timeframes and order searching features. It is frustrating that it was disabled for about two entire weeks. Searching is back to normal.
